apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theia-ide-everton-pvc
  namespace: everton
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn